# See config.example.yml for documentation.
object_base: orig/GZ3PB2
object: sys/main.dol
hash: d804d3dd5b4ff5d215e1f3b6d39e9ebfc600655b
symbols: config/GZ3PB2/symbols.txt
splits: config/GZ3PB2/splits.txt
# Change this to match the linker verison.
# See config.example.yml for a list.
mw_comment_version: 11